adminboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'adminboard'
urlpatterns = [
    path('', views.adminlogin, name='adminlogin'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('logoutAdmin/', views.logoutAdmin, name='logoutAdmin'),
    path('adminuser/', views.adminuser, name='adminuser'),
    path('addcredential/', views.addcredential, name='addcredential'),
    path('postcred/', views.postcred, name='postcred'),
    path('admineditcand/<str:username>/', views.admineditcand, name='admineditcand'),
    path('admindelcand/<str:username>/', views.admindelcand, name='admindelcand'),
    path('adminnotifycand/<str:username>/', views.adminnotifycand, name='adminnotifycand'),
    path('addquest/', views.addquest, name='addquest'),
    path('viewquest/', views.viewquest, name='viewquest'),
    path('submission/', views.submission, name='submission'),
    path('delquest/<int:quest>/', views.delquest, name='delquest'),
    path('editquest/<int:quest>/', views.editquest, name='editquest'),
    path('changequest/', views.changequest, name='changequest'),
    path('candaction/<int:id>/', views.candaction, name='candaction'),
    path('bulkupload/', views.bulkupload, name='bulkupload'),
    path('other/', views.other, name='other'),
    path('delinstructions/<int:inst>/', views.delinstructions, name='delinstructions'),
    path('postinstructions/', views.postinstructions, name='postinstructions'),
]

testingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_title = 'Test platform Admin'
admin.site.site_header = 'Test platform Admin'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('adminboard/', include('adminboard.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminboard/models.py
from django.db import models
from django.contrib.auth.models import User

class AuthorizedHr(models.Model):
    email = models.EmailField(null=True)

    def __str__(self):
        return self.email

class CreateCandidate(models.Model):
    phone = models.BigIntegerField(null=True, blank=True)
    fullname = models.CharField(max_length=300, null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    designation = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    team = models.CharField(max_length=100, null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    score = models.FloatField(null=True, blank=True)
    score_reasoning = models.FloatField(null=True, blank=True, default=0)
    score_english = models.FloatField(null=True, blank=True, default=0)
    score_math = models.FloatField(null=True, blank=True, default=0)
    invitestatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    teststatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    selectionstatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    status = models.CharField(max_length=200, null=True, blank=True, default='Pending for invite')
    dob = models.DateField(default=None, null=True, blank=True)
    resume = models.FileField(upload_to='', blank=True)
    created_at = models.DateTimeField(null=True, blank=True, default=None)
    activestatus = models.CharField(max_length=200, null=True, blank=True, default='active')
    source = models.CharField(max_length=200, null=True, blank=True)
    referralid = models.CharField(max_length=100, null=True, blank=True, default='No-referral')
    candempid = models.CharField(max_length=100, null=True, blank=True, default='Nan')
    testcomplete_at = models.DateTimeField(null=True, blank=True, default=None)



    def __str__(self):
        return self.username


class History(models.Model):
    phone = models.BigIntegerField(null=True, blank=True)
    fullname = models.CharField(max_length=300, null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    designation = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    team = models.CharField(max_length=100, null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    score = models.FloatField(null=True, blank=True)
    score_reasoning = models.FloatField(null=True, blank=True, default=0)
    score_english = models.FloatField(null=True, blank=True, default=0)
    score_math = models.FloatField(null=True, blank=True, default=0)
    invitestatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    teststatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    selectionstatus = models.CharField(max_length=200, null=True, blank=True, default='Pending')
    status = models.CharField(max_length=200, null=True, blank=True, default='Pending for invite')
    dob = models.DateField(default=None, null=True, blank=True)
    resume = models.FileField(upload_to='', blank=True)
    created_at = models.DateTimeField(null=True, blank=True, default=None)
    activestatus = models.CharField(max_length=200, null=True, blank=True, default='active')
    source = models.CharField(max_length=200, null=True, blank=True)
    referralid = models.CharField(max_length=100, null=True, blank=True, default='No-referral')
    candempid = models.CharField(max_length=100, null=True, blank=True, default='Nan')
    updated_at = models.DateTimeField(default=None, blank=True, null=True)
    updated_by = models.EmailField(default=None, blank=True, null=True)



    def __str__(self):
        return self.username



adminboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from adminboard.models import AuthorizedHr, CreateCandidate, History
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.http import HttpResponse
from datetime import datetime
from application.models import Question
from adminboard.tasks import sendmailtask
import pandas as pd
import numpy as np
from application.models import Instructions
from django.core.cache import cache
from itertools import chain
from django.core.mail import send_mail
from django.conf import settings
import smtplib  
import email.utils
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

SENDER = 'analytics@dataflowgroup.com'  
#SENDERNAME = 'Test'
#RECIPIENT  = 'ankur.singh@dataflowgroup.com'
USERNAME_SMTP = "AKIA6MOGWBGBCBL3LFR3"
PASSWORD_SMTP = "BBighTezVs/o++KjQFieuL7sJO+Xe9CmAk96KhcC2eyv"
HOST = "email-smtp.eu-west-1.amazonaws.com"
PORT = 587

def adminlogin(request):
    cache.clear()
    return render(request, 'adminboard/login.html')

def adminhome(request):
    if request.user.is_authenticated:
        obj = AuthorizedHr.objects.all()
        authorized_admin = [i.email for i in obj]
        email = request.user.email
        candidate_cont = CreateCandidate.objects.all().count()
        pending_submissions = CreateCandidate.objects.filter(invitestatus__iexact='Invite sent', teststatus__iexact='Pending')
        pending_submissions_count = pending_submissions.count()
        candidate_shortlisted = CreateCandidate.objects.filter(score__gte=70)
        candidate_shortlisted_count = candidate_shortlisted.count()
        return render(request, 'adminboard/home.html', {'first_name': request.user.first_name, 'authorized_admin': authorized_admin, 'email': email, 'candidate_count': candidate_cont,
                                                        'pending_submissions': pending_submissions, 'candidate_shortlisted':candidate_shortlisted,
                                                        'candidate_shortlisted_count': candidate_shortlisted_count,
                                                        'pending_submissions_count': pending_submissions_count})
    else:
        return redirect('adminboard:adminlogin')


def logoutAdmin(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('adminboard:adminlogin')
    else:
        return redirect('adminboard:adminlogin')

def adminuser(request):
    if request.user.is_authenticated:
        global authorized_admin
        obj = AuthorizedHr.objects.all()
        email = request.user.email
        authorized_admin = [i.email for i in obj]
        candidates = CreateCandidate.objects.all().order_by('-id')
        return render(request, 'adminboard/user.html', {'authorized_admin': authorized_admin, 'email': email, 'candidates': candidates})
    else:
        return redirect('adminboard:adminlogin')

def addcredential(request):
    if request.user.is_authenticated:
        obj = AuthorizedHr.objects.all()
        authorized_admin = [i.email for i in obj]
        email = request.user.email
        data1 = CreateCandidate.objects.all()
        data2 = User.objects.all()
        data = list(chain(data1, data2))
        return render(request, 'adminboard/cred.html', {'authorized_admin': authorized_admin, 'email':email, 'data':data})
    else:
        return redirect('adminboard:adminlogin')

@csrf_exempt
def postcred(request):
    if request.user.is_authenticated:
        authorized_admin = [i.email for i in AuthorizedHr.objects.all()]
        filler_email = request.user.email
        if request.method == 'POST' and filler_email in authorized_admin:
            fullname = request.POST.get('fullName')
            username = request.POST.get('username')
            password = request.POST.get('password')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            designation = request.POST.get('profile')
            team = request.POST.get('team')
            dob = request.POST.get('dob')
            resume = request.FILES.get('resume')
            location = request.POST.get('location')
            source = request.POST.get('source')
            referral = request.POST.get('referral')
            dob = dob[6:10] + '-' + dob[:2] + '-' + dob[3:5]
            if User.objects.filter(username=username).exists() and CreateCandidate.objects.filter(username=username).exists():
                # try:
                authcand = User.objects.get(username=username)
                authcand.first_name = fullname
                authcand.email = email
                authcand.save()
                cand = CreateCandidate.objects.get(username=username)
                cand.fullname = fullname
                cand.email = email
                cand.phone = phone
                cand.team = team
                cand.designation = designation
                cand.location = location
                cand.source = source
                cand.referralid = referral
                cand.dob = dob
                # cand.dob = dob
                if resume != None:
                    cand.resume = resume
                else:
                    pass
                cand.save()
                History.objects.create(fullname=fullname, username=username, password=password, email=email,
                                               phone=phone, designation=designation, team=team, created_at=datetime.today(),
                                               dob=dob, resume=resume, location=location, source=source,
                                               referralid=referral, updated_at=datetime.now(), updated_by=filler_email)

                # except:
                #     return HttpResponse('<h2>Error code v6s v7.5s(postcred if)</h2>')
                return redirect('adminboard:adminuser')
            else:
                # try:
                CreateCandidate.objects.create(fullname=fullname, username=username, password=password, email=email,
                                            phone=phone, designation=designation, team=team, created_at=datetime.today(), dob=dob, resume=resume, location=location, source=source, referralid=referral)
                History.objects.create(fullname=fullname, username=username, password=password, email=email,
                                               phone=phone, designation=designation, team=team, created_at=datetime.today(),
                                               dob=dob, resume=resume, location=location, source=source,
                                               referralid=referral, updated_at=datetime.now(), updated_by=filler_email)
                User.objects.create_user(first_name=fullname, username=username, password=password, email=email)

                # except:
                #     return HttpResponse('<h2>Error code v8-8.5s(postcred else)</h2>')
                return redirect('adminboard:addcredential')
        return redirect('adminboard:addcredential')
    else:
        return redirect('adminboard:adminlogin')


def admineditcand(request, username):
    if request.user.is_authenticated:
        authorized_admin = [i.email for i in AuthorizedHr.objects.all()]
        try:
            email = request.user.email
            obj = CreateCandidate.objects.get(username=username)
            return render(request, 'adminboard/editcred.html', {'candidate': obj, 'email': email, 'authorized_admin': authorized_admin})
        except:
            return HttpResponse('<h2>Error: V@admineditcand</h2>')
    else:
        return redirect('adminboard:adminlogin')


def admindelcand(request, username):
    if request.user.is_authenticated:
        authorized_admin = [i.email for i in AuthorizedHr.objects.all()]
        email = request.user.email
        if email in authorized_admin:
            # try:
            User.objects.get(username=username).delete()
            obj = CreateCandidate.objects.get(username=username)
            obj.activestatus = 'deleted'
            obj.save()
            return redirect('adminboard:adminuser')
            # except:
            #     return HttpResponse('<h2>Error: V@admindelcand</h2>')
        else:
            return HttpResponse('<h2>Error: You do not have admin rights.</h2>')
    else:
        return redirect('adminboard:adminlogin')

def adminnotifycand(request, username):
    if request.user.is_authenticated:
        authorized_admin = [i.email for i in AuthorizedHr.objects.all()]
        filler_email = request.user.email
        if filler_email in authorized_admin:
            recreate_cand = CreateCandidate.objects.get(username=username)
            if User.objects.filter(username=username).exists():
                pass
            else:
                User.objects.create_user(username=username, password=recreate_cand.password)
            
            RECIPIENT = recreate_cand.email
            msg = MIMEMultipart('alternative')
            msg['From'] = "Test <analytics@dataflowgroup.com>"
            SUBJECT = 'no-reply: Test details'
            BODY_TEXT = f'Hi {recreate_cand.fullname},\nThank you for showing interest in working with DataFlow Group.\nTo complete the application process, you are required to take an online test. The test would include assessment for English Grammar, Logic Check and Reasoning Skills.\n\nBelow are the credentials for the test:\n\nusername- {recreate_cand.username}\npassword- {recreate_cand.password}\nTest link: https://test.dfgateway.com\nThe test cannot be fragmented, but must be completed in a single attempt. The duration for the test is 45 minutes.\n\nBest Regards\nHR Team- Dataflow Group'
            msg['To'] = RECIPIENT
            part1 = MIMEText(BODY_TEXT, 'plain')
            msg.attach(part1)
            server = smtplib.SMTP(HOST, PORT)

adminboard/templates/adminboard/aside.html
<div id="grid">
    <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
</div>

<aside class="nav">
    <ul class="navbar">
        <li class="nav-items">
            <a href="{% url 'adminboard:adminhome' %}" class="list adminhome">
                <i class="fas fa-home"></i>
                Home
            </a>
        </li>
        <li class="nav-items">
            <a href="{% url 'adminboard:adminuser' %}" class="list adminuser">
                <i class="fas fa-user"></i>
                User
            </a>
        </li>
        <li class="nav-items">
            <a href="{% url 'adminboard:addquest' %}" class="list addquest">
                <i class="fas fa-book"></i>
                Question
            </a>
        </li>
        <li class="nav-items">
            <a href="{% url 'adminboard:submission' %}" class="list submissions">
                <i class="fas fa-tasks"></i>
                Finalize
            </a>
        </li>
        <li class="nav-items">
            <a href="{% url 'adminboard:other' %}" class="list other">
                <i class="fas fa-th-large"></i>
                Others
            </a>
        </li>
    </ul>
</aside>

adminboard/templates/adminboard/header.html
{% load staticfiles %}

<header class="header container-fluid">
    <div class="row admin-head">
        <div class="admin-logo col-lg-11">
            <img src="{% static 'images/DF Logo.svg' %}" alt="" width="20px" height="20px" class="mr-2">
            <a href="./home.html" class="admin-logo__h3">ADMIN BOARD</a>
        </div>

        <div class="admin-logout col-lg-1">
            <a href="{% url 'adminboard:logoutAdmin' %}" class="btn btn--logout">Logout</a>
        </div>
    </div>
</header>

adminboard/templates/adminboard/quest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="DataFlow | Candidate Testing Portal">
    {% load staticfiles %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/DF Logo.svg' %}">

    <!-- CDN CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/admin_home.css' %}">

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/11dafce953.js" crossorigin="anonymous"></script>

    <title>Questions Upload</title>
</head>
<body>

    <noscript>
        Your Browser's JavaScript has been turned off kindly enable it.
    </noscript>

    {% include 'adminboard/header.html' %}

    <main class="board container-fluid">
        
        {% include 'adminboard/aside.html' %}

        <div class="screen">
            <div class="screen__table">
                <div class="screen__table__top">
                    <h3 class="table-title">Question Bank</h3>
                    <a href="{% url 'adminboard:viewquest' %}" class="a--back"><i class="fas fa-chevron-left pr-2"></i> View Questions</a>
                </div>

                <div class="tab">
                    <ul class="tabs-nav">
                        <span class="back-span"></span>
                        <li class="tab-items" data-id="single">Single Upload</li>
                        <li class="tab-items" data-id="bulk">Bulk Upload</li>
                    </ul>
                </div>
                {% block question %}
                    <div class="drag hidden">
                        <form action="{% url 'adminboard:bulkupload' %}" method="post" id="bulk-form" enctype="multipart/form-data">{% csrf_token %}
                            <div class="form-group inputDnD">
                                <label class="sr-only" for="inputFile">File Upload</label>
                                <input type="file" name="bulk" class="form-control-file text-primary font-weight-bold" id="inputFile" accept=".csv" onchange="readUrl(this)" data-title="Drag and drop a file">
                            </div>

                            <div class="btn-div mt-4">
                                <button type="submit" class="btn btn--success">Upload</button>
                            </div>
                        </form>
                    </div>
                    <div class="normal">
                        <form action="{% url 'adminboard:addquest' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form2">
                                <div class="form-div">
                                    <label for="question" class="form-label">Question</label>
                                    <textarea name="question" id="question" class="form-elem form-textarea"></textarea>
                                </div>

                                <div class="form">
                                    <div class="form-div">
                                        <label for="opt1" class="form-label">Option1</label>
                                        <input type="text" name="opt1" id="opt1" class="form-elem" required="required">
                                    </div>
                                    <div class="form-div">
                                        <label for="opt2" class="form-label">Option2</label>
                                        <input type="text" name="opt2" id="opt2" class="form-elem" required="required">
                                    </div>
                                    <div class="form-div">
                                        <label for="opt3" class="form-label">Option3</label>
                                        <input type="text" name="opt3" id="opt3" class="form-elem" required="required">
                                    </div>
                                    <div class="form-div">
                                        <label for="opt4" class="form-label">Option4</label>
                                        <input type="text" name="opt4" id="opt4" class="form-elem" required="required">
                                    </div>
                                    <div class="form-div">
                                        <label for="opt5" class="form-label">Option5</label>
                                        <input type="text" name="opt5" id="opt5" class="form-elem">
                                    </div>
                                    <div class="form-div">
                                        <label for="correct" class="form-label">Correct Option</label>
                                        <input type="text" name="correct" id="correct" class="form-elem" required="required">
                                    </div>
                                    <div class="form-div">
                                        <label for="category" class="form-label">Category</label>
                                        <select name="category" id="category" class="form-elem" required="required">
                                            <option value="">--select--</option>
                                            <option value="English">English (Comprehension)</option>
                                            <option value="Reasoning">Reasoning</option>
                                            <option value="Psychometric">Quantitative</option>
                                        </select>
                                    </div>
                                </div>

                            </div>

                            <div class="btn-div mt-4">
                                <button type="submit" class="btn btn--success">Submit</button>
                                <button type="reset" class="btn btn--reset">Reset</button>
                            </div>
                        </form>
                    </div>
                {% endblock %}


            </div>
        </div>
    </main>


    <!-- Script
    ------------------------>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="{% static 'js/admin/admin.js' %}"></script>
    <script src="{% static 'js/admin/tab.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>

adminboard/templates/adminboard/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="DataFlow | Candidate Testing Portal">
    {% load staticfiles %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/DF Logo.svg' %}">

    <!-- CDN CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedcolumns/3.3.0/css/fixedColumns.bootstrap.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/admin_home.css' %}">

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/11dafce953.js" crossorigin="anonymous"></script>

    <title>User Panel</title>
</head>
<body>
    <noscript>
        Your Browser's JavaScript has been turned off kindly enable it.
    </noscript>

    {% include 'adminboard/header.html' %}

    {% if email in authorized_admin %}
    <main class="board container-fluid">

        {% include 'adminboard/aside.html' %}

        <div class="screen">
            <div class="screen__table invite">
                <div class="screen__table__top">
                    <h3 class="table-title">All Credentials</h3>
                    <a href="{% url 'adminboard:addcredential' %}" class="btn btn--create"> <i class="fas fa-plus pr-2"></i> Add Credentials</a>
                </div>

                <table class="table dt-responsive nowrap" id="CCTable">
                    <thead>
                        <tr>
                            <th scope="row">Name</th>
                            <th scope="row">Email</th>
                            <th scope="row">D.O.B</th>
                            <th scope="row">Phone</th>
                            <th scope="row">Designation</th>
                            <th scope="row">Team</th>
                            <th scope="row">Location</th>
                            <th scope="row">Source</th>
                            <th scope="row">Status</th>
                            <th scope="row">Test complete at</th>
                            <th scope="row">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for i in candidates %}
                        <tr>
                            <td>{{ i.fullname }}</td>
                            <td>{{ i.email }}</td>
                            <td>{{ i.dob }}</td>
                            <td>{{ i.phone }}</td>
{#                            <td><a href="/static/media/{{ i.resume }}" target="_blank">View Resume</a></td>#}
                            <td>{{ i.designation }}</td>
                            <td>{{ i.team }}</td>
                            <td>{{ i.location }}</td>
                            <td>{% if i.source == 'Referral'%}
                                    {{ i.referralid }}
                                {% else %}
                                    {{ i.source }}
                                {% endif %}
                            </td>
                            <td class="inv">{{ i.status }}</td>
                            <td>{{ i.testcomplete_at }}</td>
                            <td>
                                <a href="{% url 'adminboard:admineditcand' username=i.username %}" class="pr-2 edit"><i class="fas fa-edit" title="edit"></i></a>
                                <a href="{% url 'adminboard:adminnotifycand' username=i.username %}" class="pl-2 plane"><i class="fas fa-paper-plane" title="send"></i></a>
                                <a class="loader pl-2 hidden"><i class="fas fa-circle-notch"></i></a>
<!--                                <a href="{% url 'adminboard:admindelcand' username=i.username %}" class="delete"><i class="fas fa-trash-alt" title="delete"></i></a>-->
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    {% else %}<h1>Get Out</h1>
    {% endif %}


    <!-- Script
    ------------------------>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/fixedcolumns/3.3.0/js/dataTables.fixedColumns.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

    <script src="{% static 'js/admin/admin.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#CCTable').DataTable({
                "scrollX": true,
                fixedColumns:   {
                    leftColumns: 1,
                    rightColumns: 0
                }
            });
            // $('#ACTable').DataTable({
            //     "scrollX": true,
            //     fixedColumns:   {
            //         leftColumns: 1,
            //         rightColumns: 0
            //     },
            //     dom: 'Bfrtip',
            //     buttons: [
            //         'csv'
            //     ],
            // });
        });
    </script>
</body>
</html>