adminboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'adminboard'
urlpatterns = [
    path('', views.adminlogin, name='adminlogin'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('logoutAdmin/', views.logoutAdmin, name='logoutAdmin'),
    path('adminuser/', views.adminuser, name='adminuser'),
    path('addcredential/', views.addcredential, name='addcredential'),
    path('postcred/', views.postcred, name='postcred'),
    path('admineditcand/<str:username>/', views.admineditcand, name='admineditcand'),
    path('admindelcand/<str:username>/', views.admindelcand, name='admindelcand'),
    path('adminnotifycand/<str:username>/', views.adminnotifycand, name='adminnotifycand'),
    path('addquest/', views.addquest, name='addquest'),
    path('viewquest/', views.viewquest, name='viewquest'),
    path('submission/', views.submission, name='submission'),
    path('delquest/<int:quest>/', views.delquest, name='delquest'),
    path('editquest/<int:quest>/', views.editquest, name='editquest'),
    path('changequest/', views.changequest, name='changequest'),
    path('candaction/<int:id>/', views.candaction, name='candaction'),
    path('bulkupload/', views.bulkupload, name='bulkupload'),
    path('other/', views.other, name='other'),
    path('delinstructions/<int:inst>/', views.delinstructions, name='delinstructions'),
    path('postinstructions/', views.postinstructions, name='postinstructions'),
]

application/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'application'
urlpatterns = [
    path('', views.applogin, name='applogin'),
    path('signup/', views.appsignup, name='appsignup'),
    path('postsignup/', views.postsignup, name='postsignup'),
    path('logincand/', views.logincand, name='logincand'),
    path('instructions/', views.instructions, name='instructions'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('panel/', views.panel, name='panel'),
    path('submitted/', views.submitted, name='submitted'),
    path('forcelogout/<str:username>/', views.forcelogout, name='forcelogout'),
]

testingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_title = 'Test platform Admin'
admin.site.site_header = 'Test platform Admin'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('adminboard/', include('adminboard.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/models.py
from django.db import models

class Question(models.Model):
    category = models.CharField(max_length=200, null=True, blank=True)
    question = models.TextField(null=True, blank=True)
    option1 = models.TextField(null=True, blank=True)
    option2 = models.TextField(null=True, blank=True)
    option3 = models.TextField(null=True, blank=True)
    option4 = models.TextField(null=True, blank=True)
    option5 = models.TextField(default='null', null=True, blank=True)
    correct = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.category


class Tagquestion(models.Model):
    username = models.CharField(max_length=100, null=True, blank=True)
    quesid = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.username

class Instructions(models.Model):
    points = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.points

application/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from application.models import Question
from adminboard.models import CreateCandidate, History
from django.http import HttpResponse
from django.contrib.auth.models import User
from application.models import Instructions
from django.core.cache import cache
from datetime import datetime
from django.core.serializers.json import DjangoJSONEncoder
import json
from django.core.mail import send_mail
from django.conf import settings
from itertools import chain
import numpy as np
from django.db.models import Count
import math


def applogin(request):
    return render(request, 'application/index.html')

def appsignup(request):
    data1 = CreateCandidate.objects.all()
    data2 = User.objects.all()
    data = list(chain(data1, data2))
    return render(request, 'application/signup.html', {'data': data})

@csrf_exempt
def postsignup(request):
    if request.method == 'POST':
        fullname = request.POST.get('fullName')
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        dob = request.POST.get('dob')
        resume = request.FILES.get('resume')
        location = request.POST.get('location')
        source = request.POST.get('source')
        referral = request.POST.get('referral')
        dob = dob[6:10] + '-' + dob[:2] + '-' + dob[3:5]
        CreateCandidate.objects.create(fullname=fullname, username=username, password=password, email=email,
                                       phone=phone, created_at=datetime.today(),
                                       dob=dob, resume=resume, location=location, source=source, referralid=referral, invitestatus='Invite sent', status='Invite sent')
        History.objects.create(fullname=fullname, username=username, password=password, email=email,
                               phone=phone, created_at=datetime.today(),
                               dob=dob, resume=resume, location=location, source=source,
                               referralid=referral, updated_at=datetime.now(), invitestatus='Invite sent', status='Invite sent')
        User.objects.create_user(first_name=fullname, username=username, password=password, email=email)
        sub = 'no-reply: Test details'
        content = f'Hi {fullname},\nThank you for showing interest in working with DataFlow Group.\nTo complete the application process, you are required to take an online test. The test would include assessment for English Grammar, Logic Check and Reasoning Skills.\n\nBelow are the credentials for the test:\n\nusername- {username}\npassword- {password}\nTest link: https://test.dfgateway.com\nThe test cannot be fragmented, but must be completed in a single attempt. The duration for the test is 45 minutes.\n\nBest Regards\nHR Team- Dataflow Group'
        tomail = [f'{email}']
        # sendmailtask.delay(sub, content, tomail)

        # send_mail(sub, content, settings.EMAIL_HOST_USER, tomail)
        return redirect('application:applogin')
    return redirect('application:appsignup')

@csrf_exempt
def logincand(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('application:instructions')
        else:
            messages.error(request, "Incorrect Credentials")
            return redirect('application:applogin')
    return redirect('application:applogin')

@login_required(login_url='logincand/')
def instructions(request):
    username = request.user.username
    obj = CreateCandidate.objects.get(username=username)
    instruct = Instructions.objects.all().order_by('-id')
    return render(request, 'application/instructions.html', {'username': username, 'name': obj.fullname, 'email': obj.email, 'phone': obj.phone, 'instruct': instruct})

@login_required(login_url='logincand/')
def logout_user(request):
    logout(request)
    return redirect('application:applogin')

@login_required(login_url='logincand/')
def panel(request):
    username = request.user.username
    # comp_count = Question.objects.values('question').filter(category__iexact='english').annotate(Count('id')).filter(id__count__gte=2).count()
    comp_count = [i for i in Question.objects.filter(category__iexact='english') if len(i.question) > 2000]
    if len(comp_count) > 0:
        nocomp_quest = [j.id for j in Question.objects.filter(category__iexact='english') if len(j.question) < 1000]
        english = Question.objects.filter(pk__in=nocomp_quest).order_by('?')[:8]
        random_count = np.random.randint(len(comp_count))
        comp_quest = [i.question for i in Question.objects.filter(category__iexact='english') if len(i.question) > 2000]
        comprehensive = Question.objects.filter(question__icontains=comp_quest[random_count][:1000])[:2]
        english_questions = list(chain(english, comprehensive))
    else:
        nocomp_quest = [j.id for j in Question.objects.filter(category__iexact='english') if len(j.question) < 1000]
        english_questions = Question.objects.filter(pk__in=nocomp_quest).order_by('?')[:10]

    quantitative_questions = Question.objects.filter(category__iexact='quantitative').order_by('?')[:10]
    reasoning_questions = Question.objects.filter(category__iexact='reasoning').order_by('?')[:10]
    return render(request, 'application/panel.html', {'english_questions': english_questions, 'quantitative_questions': quantitative_questions,
                                                      'reasoning_questions': reasoning_questions, 'username': username})

@login_required(login_url='logincand/')
@csrf_exempt
def submitted(request):
    if request.method == 'POST':
        percent_reas = request.POST.get('vichar__')
        percent_eng = request.POST.get('angrezi__')
        percent_math = request.POST.get('ganith__')
        username = request.POST.get('username__')
        # try:
        user = CreateCandidate.objects.get(username=username)
        user.score_reasoning = math.ceil(int(percent_reas)/10 * 100)
        user.score_english = math.ceil(int(percent_eng)/10 * 100)
        user.score_math = math.ceil(int(percent_math)/10 * 100)
        percent = math.ceil(((int(percent_reas) + int(percent_eng) + int(percent_math))/30) * 100)
        user.score = percent
        user.teststatus = 'Test Taken'
        user.status = 'Test Taken'
        user.testcomplete_at= datetime.now()
        user.save()
        History.objects.create(username=user.username, password=user.password,
                                          phone=user.phone, fullname=user.fullname, designation=user.designation,
                                          email=user.email, team=user.team, location=user.location, score=user.score,
                                          score_reasoning=percent_reas, score_english=percent_eng, score_math=percent_math,
                                          invitestatus=user.invitestatus, teststatus='Test Taken',
                                          status='Test Taken', dob=user.dob, resume=user.resume, created_at=user.created_at,
                                          activestatus=user.activestatus, selectionstatus=user.selectionstatus, source=user.source, referralid=user.referralid,
                                          candempid=user.candempid, updated_at=datetime.now(), updated_by=user.email)
        # except:
        #     return HttpResponse('<h2>Unique contraint failed for username</h2>')
        logout(request)
        return render(request, 'application/submit.html', {'score': percent})
    return redirect('application:panel')


def forcelogout(request, username):
    User.objects.get(username=username).delete()
    CreateCandidate.objects.filter(username__exact=username).update(status='force-logout')
    logout(request)
    return render(request, 'application/forcelogout.html')

application/templates/application/base_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="DataFlow | Candidate Testing Portal">

    {% load staticfiles %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/DF Logo.svg' %}">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css" integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <noscript>
        Your Browser's JavaScript has been turned off kindly enable it.
    </noscript>
    
    <div class="front-page">
        <section class="front-page--hero">
            <div class="logo-nav">
                <img src="{% static 'images/DF Logo.svg' %}" alt="logo" class="logo-image">
                <p class="logo-title"><span class="logo-title--1">Data</span>flow</p>
            </div>
            <img src="{% static 'images/portal-hero.svg' %}" alt="portal" class="portal--hero">
        </section>
        
        <section class="front-page--content">
            {% block body %}{% endblock %}
        </section>
    </div>

    <!-- Script -->
    <script src="{% static 'js/user/index.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>

application/templates/application/forcelogout.html
{% extends 'application/submit.html' %}
{% block result %}
    <style>
        #rocket{
            opacity: 0;
        }

      .forced{
        color: #ccc;
      }
    </style>
    <h2 class="forced">Due to force Escape or Reload, your test has been submitted. <br>If not intentional please contact Dataflow- HR Team</h2>
{% endblock %}

application/templates/application/header.html
{% load staticfiles %}

<header class="header">
    <div class="logo">
        <span class="navbar-brand">Candidate Portal</span>
    </div>
    <nav class="navbar">
        <ul class="nav">
            <li class="nav-items active"><a href="">Assessment</a></li>
            <li class="nav-items logout-btn"><a href="{% url 'application:logout_user' %}">Logout</a></li>
        </ul>
    </nav>
</header>

application/templates/application/index.html
{% extends "application/base_login.html" %}
{% load staticfiles %}

{% block title %}Login | Candidate Portal{% endblock %}

{% block body %}

<div class="form-section">
    <section class="form-title">
        <p class="form-title--pre">Welcome</p>
        <p class="form-title--heading"><span>Login to</span><span>Candidate Portal</span></p>
    </section>
    <section class="form-login">
        <form action="{% url 'application:logincand' %}" method="POST" class="login-form" id="loginForm">
            {% csrf_token %}
            {% for message in messages %}
            <div class="alert alert-danger error-message">
                <a class="close" href="#" data-dismiss="alert"></a>
                <p>{{ message }}</p>
            </div>
            {% endfor %}
            
            <div class="form-component">
                <input type="text" name="username" class="input-field" autocomplete="off" required>
                <span class="label-placeholder">Username</span>
            </div>

            <div class="form-component">
                <input type="password" name="password" class="input-field" autocomplete="off" required>
                <span class="label-placeholder">Password</span>
                <span class="password-eye" title="Show Password">
                    <i class="fas fa-eye-slash"></i>
                </span>
            </div>

            <div class="form-bottom">
                <button type="submit" class="btn--primary" id="loginBtn">Login</button>
                <p class="goto-signup">Don't have an account? <a href="{% url 'application:appsignup' %}">Register</a></p>
            </div>
        </form>
    </section>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/user/interactive.js' %}"></script>
{% endblock %}

application/templates/application/instructions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="DataFlow | Candidate Testing Portal">
    {% load staticfiles %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/DF Logo.svg' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/11dafce953.js" crossorigin="anonymous"></script>

    <title>Instructions | Candidate Portal</title>
</head>
<body>
    <noscript>
        Your Browser's JavaScript has been turned off kindly enable it.
    </noscript>

    <div class="app">

        {% include 'application/header.html' %}

        <main class="render">

            <section class="user-data mb-4">
                <p class="user-data-head mb-2">Candidate Details</p>
                <div class="brief">
                    <div class="brief-box">
                        <p class="tag">Name:</p>
                        <p class="tag-value">{{ name }}</p>
                    </div>
                    <div class="brief-box">
                        <p class="tag">Email:</p>
                        <p class="tag-value">{{ email }}</p>
                    </div>
                    <div class="brief-box">
                        <p class="tag">Phone no:</p>
                        <p class="tag-value">{{ phone }}</p>
                    </div>
                </div>
            </section>
            <section class="instruction-data mb-4">
                <p class="instructuion-data-head mb-2">Instructions</p>
                <div class="instructions">
                    <p class="imp-note">Note: Read through instructions given below carefully before attempting test</p>
                    <ul class="instruction-list">
                        {% for i in instruct %}
                            <li>{{ i }}</li>
                        {% endfor %}
                    </ul>
                    <strong class="wishes">BEST OF LUCK (づ ◕‿◕ )づ</strong>
                </div>
            </section>

            <section class="declaration-data mb-4">
                <p class="declaration-data-head mb-2">Declaration</p>
                <div class="declaration">
                    <p class="mb-1">I hereby provide my consent to the use of my personal information provided in my job application for the purpose of conducting the recruitment process with DataFlow.</p>
                    <p>
                        By sharing personal information with applicable details, I acknowledge and agree that the information I have submitted is complete and correct to the best of my knowledge. 
                        I agree that providing false information in the creation of my job profile or during the application process will lead to my rejection or termination. 
                        I hereby agree/ disagree to use of my personal data for above mentioned purpose by responding back to this email:
                    </p>

                    <p class="more-info mt-3">
                        For more information about our privacy practices, please visit our website Landing - <a href="https://corp.dataflowgroup.com/" class="text-blue-600 underline">Dataflow Group</a> or our website privacy policy <a href="https://corp.dataflowgroup.com/about-us/our-policies/general-applicant-privacy-policy/" class="text-blue-600 underline">General Applicant Privacy Policy - Dataflow Group</a>.
                    </p>
                </div>
            </section>


            
            
            <div class="agreement-box">
                <input type="checkbox" id="declartion" name="declartion">
                <label for="declartion">I agree to the above declration</label>
            </div>

            <button class="btn--primary start-test" disabled>Start Test<i class="fas fa-chevron-right"></i></button>

        </main>

        <section class="start-test-info">
            <div class="overlay-sect">
                <p class="title">Make an attempt</p>
                <div class="cold-info">
                    <p>This test has a time limit of 60mins. Count down will start the moment you start the test. You've to submit the test within 60 minutes or else it will automatically get submitted.</p><br>
                    <strong>Are you sure you wish to start now?</strong>
                </div>
                <div class="buttons">
                    <a href="{% url 'application:panel' %}" class="btn--primary text-center">Continue</a>
                    <a class="btn--cancel text-center cancel-no">Cancel</a>
                </div>
            </div>
        </section>

    </div>
    
    <!-- Script -->
    <script src="{% static 'js/user/interactive.js' %}"></script>
    <script src="{% static 'js/user/inspect.js' %}"></script>

</body>
</html>

application/templates/application/result.html
<script defer>
    let vichar = [], angrezi = [], ganith = [];
    const form = document.querySelector('#panelForm');
    {% for i in reasoning_questions %}
        rObj = {};rObj[`01`] = `{{ i.id }}`;rObj[`02`] = `{{ i.correct }}`;vichar.push(rObj);
    {% endfor %}



    {% for i in quantitative_questions %}
        qObj = {};qObj[`01`] = `{{ i.id }}`;qObj[`02`] = `{{ i.correct }}`;ganith.push(qObj);
    {% endfor %}
        {% for i in english_questions %}
        eObj = {};eObj[`01`] = `{{ i.id }}`;eObj[`02`] = `{{ i.correct }}`;angrezi.push(eObj);
    {% endfor %}

    const s = document.querySelector('#nextBtn');
    const p = document.querySelectorAll('.panel');
    const pv = document.querySelectorAll('.data-v-pv');
    const pa = document.querySelectorAll('.data-v-pa');
    const pg = document.querySelectorAll('.data-v-pg');
    const pr = document.querySelector('.parinam');
    const an = document.querySelector('.angrezi');
    const ga = document.querySelector('.ganith');
    const vi = document.querySelector('.vichar');

    let ipv = 0, ipa = 0, ipg = 0, antha = 0;

    function score(){

        for(let i=0; i<pv.length; i++){
            opt = pv[i].querySelectorAll('.optBtn');
            [...opt].map(o => {
               if(o.checked){
                   v = o.value;
                   x = vichar[i]["02"];
                   if(v === x){
                       ipv++;    //int stat increases by 1 point
                   }
               }
            });
        }

        for(let i=0; i<pa.length; i++){
            opt = pa[i].querySelectorAll('.optBtn');
            [...opt].map(o => {
               if(o.checked){
                   v = o.value;
                   x = angrezi[i]["02"];
                   if(v === x){
                       ipa++;    //int stat increases by 1 point
                   }
               }
            });
        }

        for(let i=0; i<pg.length; i++){
            opt = pg[i].querySelectorAll('.optBtn');
            [...opt].map(o => {
               if(o.checked){
                   v = o.value;
                   x = ganith[i]["02"];
                   if(v === x){
                       ipg++;    //int stat increases by 1 point
                   }
               }
            });
        }

        antha = ipv + ipa + ipg;
        vi.value = ipv;
        an.value = ipa;
        ga.value = ipg;

    }

    form.addEventListener('submit', e => {
        e.preventDefault();
        score();
        const subBtn = document.querySelector('#submitBtn');
        subBtn.innerHTML = `<i class="fas fa-circle-notch load-icon"></i> Submitting`;
        subBtn.setAttribute('type', 'button');
        form.submit();
    });


</script>

application/templates/application/signup.html
{% extends "application/base_login.html" %}
{% load staticfiles %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}SignUp | Candidate Portal{% endblock %}

{% block body %}

<div class="signup-section">
    <h4>Create an account on Candidate Portal</h4>
    <p>Please check your mail for login credentails after signing up</p>

    <form action="{% url 'application:postsignup' %}" method="POST" class="signup-form form cred-form" id="credForm" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="signup-form-section">
            <div class="form-div">
                <label for="" class="form-label">Full Name</label>
                <input type="text" name="fullName" class="form-elem form-elem--name" data-id="name" autocomplete="off" placeholder="John Doe">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Username</label>
                <input type="text" name="username" class="form-elem form-elem--user" data-id="username" autocomplete="off" placeholder="johndoe">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Password
                </label>
                <input type="password" name="password" class="form-elem form-elem--pass" data-id="pass" autocomplete="off" placeholder="********">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Email</label>
                <input type="text" name="email" class="form-elem form-elem--email" data-id="email" autocomplete="off" placeholder="john.doe@gmail.com">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Phone Number</label>
                <input type="number" name="phone" class="form-elem form-elem--mobile" data-id="mobile" maxlength='10' minlength='10' autocomplete="off" placeholder="9876543210">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Date of Birth</label>
                <input type="" name="dob" class="form-elem form-elem--dob form-control" id="dob" data-id="dob" autocomplete="off" placeholder="mm/dd/yyyy">
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Location</label>
                <select name="location" id="location" class="form-elem custom-select" data-id="location">
                    <option value="">--select location--</option>
                    <option value="Noida">Noida</option>
                    <option value="Jordan">Jordan</option>
                    <option value="Manila">Manila</option>
                    <option value="Bangkok">Bangkok</option>
                    <option value="Dubai">Dubai</option>
                    <option value="Hyderabad">Hyderabad</option>
                    <option value="KSA">KSA</option>
                    <option value="Qatar">Qatar</option>
                    <option value="Singapore">Singapore</option>
                    <option value="Mumbai">Mumbai</option>
                    <option value="UK">UK</option>		
                </select>
                <span class="note"></span>
            </div>

            <div class="form-div">
                <label for="" class="form-label">Source</label>
                <select name="source" id="source" class="form-elem custom-select" data-id="source">
                    <option value="">--select source--</option>
                    <option value="Referral">Referral</option>
                    <option value="Direct Sourcing">Direct Sourcing</option>
                    <option value="Consultant">Consultant</option>
                    <option value="Social Media">Social Media</option>
                </select>
                <span class="note"></span>
            </div>

            <div class="form-div hidden">
                <label for="" class="form-label">Referral ID</label>
                <input type="text" name="referral" class="form-elem form-elem--refer" data-id="referral" autocomplete="off">
                <span class="note"></span>
            </div>

            <div class="form-div position-relative">
                <label class="form-label">Upload Resume (pdf only)</label>
                <input type="file" name="resume" class="custom-file-input form-elem form-elem--resume" id="customFile resume" data-id="resume" accept=".pdf">
                <label class="custom-file-label form-elem" for="customFile" data-id="dResume">Choose file</label>
                <span class="note"></span>
            </div>
        </div>
        <div class="form-bottom mt-4">
            <button type="submit" class="btn--primary" id="register">Register</button>
            <p class="goto-login">Already have an account? <a href="{% url 'application:applogin' %}">Login</a></p>
        </div>
    </form>
</div>

{% endblock %}

{% block script %}
<script>
    // u - username, m - email, p - phone
    const u=[], m=[], p=[];
    {% for i in data %} 
        u.push(`{{ i.username }}`);
        m.push(`{{ i.email }}`);
        p.push(`{{ i.phone }}`);
    {% endfor %}

    // Datepicker
    $('#dob').datepicker();

    //File upload name
    $(".custom-file-input").on("change", function() {
        let fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>
<script src="{% static 'js/user/validation.js' %}"></script>
{% endblock %}